<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2014-07-26 09:21:25
 */
return [
    'app\\assets\\AllAsset' => [
        'basePath' => '/vagrant/web',
        'js' => [
            'compiled-assets/all-dcf8c375a5b81e46e0b8fb301717d654.js',
        ],
        'css' => [
            'compiled-assets/all-4d8400dcee8e562bfa9b73a62b2fc9f9.css',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\ApplicationUiAssetBundle' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\grid\\GridViewAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
];