<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2014-08-03 09:02:10
 */
return [
    'app\\assets\\AllAsset' => [
        'basePath' => '/vagrant/web',
        'js' => [
            'compiled-assets/all-5874c2e16373c2cb45f6a1eea5eafcb4.js',
        ],
        'css' => [
            'compiled-assets/all-415b83930ed65608300c8fc5a649562e.css',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\AuditColumnAssetsBundle' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\ApplicationUiAssetBundle' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\grid\\GridViewAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
];